
name: Kneed for Speed Workflow

#Run the workflow when there is a push or pull request for the main branch
on: 
  # We shouldn't be committing anything directly to main without submitting
  # pull requests. The workflow is currently setup to lint only on new code
  # so its a bit silly to run the workflow on push when its already covered the
  # code base being pushed in the pull request.
  # push: 
  #   branches: [main]
  pull_request:
    branches: [main]
    paths-ignore:
      - 'docs/**'
      - 'data/**'
      - 'img/**'

#One job named lint
jobs:
  #Runs the github Super-Linter and test.sh files on our repository code (linter runs only on newly submited code, change this by removing the line
  #"VALIDATE_ALL_CODEBASE: false").
  lint:
    #Run in a ubuntu container and timeout if the job isn't done after two minutes
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        node-version:  [14.x, 16.x, 19.x]

    #Checkout the entire repository history
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      #Run the super-linter on newly submitted code
      - name: Super-Linter
        uses: github/super-linter@v4.9.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          #OUTPUT_FOLDER: Reports
          OUTPUT_DETAILS: detailed
          VALIDATE_ALL_CODEBASE: false

      #Run the test.sh file using the container's commands
      - name: Use node.js $ {{ matrix.nodeversion }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.nodeversion }}
          cache: 'npm'
      - run: npm ci
      - run: npm test